<a href="https://colab.research.google.com/github/OHTORO87/ai_class/blob/main/colab_d12_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 시작하기전에 해야할일

In [2]:
import pandas as pd
import numpy as np
#시작하면 항상 이거 2개 치고 시작

n1 = numpy 1차원,
s1 = series,
d1 = dataframe.

이런식으로 이름 지어주자


In [9]:
n1 = np.random.randint(0, 100, 10)

In [10]:
type(n1)

numpy.ndarray

In [11]:
n1.shape

(10,)

In [12]:
n1.ndim

1

In [13]:
n1.size

10

In [14]:
n1.nbytes

80

In [16]:
n1.itemsize

8

In [17]:
n = n1.copy()

In [18]:
n[:]

array([21, 39, 26, 77, 26, 30, 42, 61, 94, 73])

In [19]:
n[0:10]

array([21, 39, 26, 77, 26, 30, 42, 61, 94, 73])

In [20]:
n[0:10:2]

array([21, 26, 26, 42, 94])

In [21]:
n[0:10:3]

array([21, 77, 42, 73])

In [22]:
n[::-1]

array([73, 94, 61, 42, 30, 26, 77, 26, 39, 21])

In [23]:
n[::-2]

array([73, 61, 30, 77, 39])

In [24]:
n.reshape(2, 5)

array([[21, 39, 26, 77, 26],
       [30, 42, 61, 94, 73]])

In [25]:
n.reshape(5, 2)

array([[21, 39],
       [26, 77],
       [26, 30],
       [42, 61],
       [94, 73]])

In [26]:
n.reshape(3, 3)
#n이 10개여서 3x3으로 출력 불가

ValueError: ignored

In [29]:
n1.sort()

In [30]:
n1

array([21, 26, 26, 30, 39, 42, 61, 73, 77, 94])

In [31]:
n1.sort(axis=1)
#1차원이라 axis가 없어서 에러남

AxisError: ignored

In [33]:
n1.sort?
# ? 도움말

In [34]:
n2 = np.random.randint(1, 100, 12)

In [35]:
n2

array([45, 88, 87, 10, 84, 31,  2, 55,  8, 31, 89, 38])

In [36]:
n2.reshape(3, 4)

array([[45, 88, 87, 10],
       [84, 31,  2, 55],
       [ 8, 31, 89, 38]])

In [37]:
n2.reshape(2, 6)

array([[45, 88, 87, 10, 84, 31],
       [ 2, 55,  8, 31, 89, 38]])

In [38]:
n2.reshape(4, 3)

array([[45, 88, 87],
       [10, 84, 31],
       [ 2, 55,  8],
       [31, 89, 38]])

# 아 이거 기억 잘해놓자

# int16 = 2byte

In [40]:
n21 = np.arange(1, 17, dtype=np.int16)

In [41]:
n21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int16)

In [43]:
n = n21.reshape(4, 4)

In [44]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [45]:
n[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [46]:
n[ : , : ]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [47]:
n[0,3]

4

In [48]:
n[0:2,1:3]

array([[2, 3],
       [6, 7]], dtype=int16)

In [49]:
n[1:5, 2:5]

array([[ 7,  8],
       [11, 12],
       [15, 16]], dtype=int16)

In [51]:
n[2:,0:2]

array([[ 9, 10],
       [13, 14]], dtype=int16)

In [53]:
n[0,1:3]

array([2, 3], dtype=int16)

In [54]:
n[2:,1:3]

array([[10, 11],
       [14, 15]], dtype=int16)

In [55]:
a = [2, 3, 5]

In [58]:
S = 0

# 특정 데이터에 연산이 가능하다

In [59]:
n[2:4, 1:3]*3
# 특정 데이터에 연산이 가능하다

array([[30, 33],
       [42, 45]], dtype=int16)

In [60]:
n[2:4, 1:3] == 0


array([[False, False],
       [False, False]])

In [62]:
n[0]

array([1, 2, 3, 4], dtype=int16)

In [63]:
n[0] < 5

array([ True,  True,  True,  True])

In [64]:
n > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [65]:
n[0][0] == 100

False

In [71]:
n[:,0:1]
# n[:, 0] 하고 결과가 다르다

array([[ 1],
       [ 5],
       [ 9],
       [13]], dtype=int16)

In [73]:
n[0][3] = 44

In [74]:
n

array([[ 1,  2,  3, 44],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [75]:
n[:, 3] = 100
# n[:, -1] 도 같은 결과 나옴

In [76]:
n

array([[  1,   2,   3, 100],
       [  5,   6,   7, 100],
       [  9,  10,  11, 100],
       [ 13,  14,  15, 100]], dtype=int16)

# 합계 구하기

In [77]:
n[0].sum()
# 0행의 총합

106

In [78]:
n.max()

100

In [79]:
n.max(axis=1)

array([100, 100, 100, 100], dtype=int16)

In [80]:
n.max(axis=0)

array([ 13,  14,  15, 100], dtype=int16)

In [81]:
n.mean()

31.0

In [83]:
n.std()

40.03123780249619

In [84]:
n.var()

1602.5

In [86]:
np.median(n)

10.5

In [87]:
np.median(n[0])
# 0행에서의 중앙값

2.5

In [88]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [89]:
np.ones(5)
# 제로하고 원스만 있따

array([1., 1., 1., 1., 1.])

In [94]:
np.tri(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
np.empty(6)
# 비어있는 공간을 6개 가지고 온거임
# 나중에 채우려고 빈 공간을 만들어낸것

array([4.68887684e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [98]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## bytes 알아보는법

In [103]:
n7 = np.array([4,5,6,7])

In [106]:
n7.nbytes

32

In [107]:
n8 = np.array([4,5,6,7], np.int32)

In [108]:
n8.nbytes

16

In [109]:
k = [i for i in range(5, 51, 5)]

In [110]:
k

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [111]:
type(k)

list

In [112]:
t = (i for i in range(10, 101, 10))

In [113]:
t

<generator object <genexpr> at 0x7fbecbb5ea50>

In [120]:
type(t)
# list가 가지고 있는 주소값을 알려줌?
# generator

generator

In [115]:
n10 = np.array(k)

In [117]:
n10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [118]:
np.array(t)

array(<generator object <genexpr> at 0x7fbecbb5ea50>, dtype=object)

In [119]:
t

<generator object <genexpr> at 0x7fbecbb5ea50>

In [126]:
n12 = np.array(k)

# 시리즈 시작

In [127]:
s1 = pd.Series([2, 4, 6, 8])

In [129]:
type(s1)
# 데이터의 구조를 먼저 파악하라

pandas.core.series.Series

In [130]:
s1.shape

(4,)

In [131]:
s1.ndim

1

In [132]:
s1.nbytes

32

In [133]:
s1.items

<bound method Series.items of 0    2
1    4
2    6
3    8
dtype: int64>

In [134]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [136]:
s1
# 좌측 인덱스, 우측이 값
# 인덱스 묵시적으로 0,1,2,3으로 지정됨(디폴트값)

0    2
1    4
2    6
3    8
dtype: int64

In [140]:
s1.index=[['T', 'K', 'B', 'Q']]
# 인덱스 명시적 지정

In [141]:
s1
# 인덱스를 지정할수 있따.

T    2
K    4
B    6
Q    8
dtype: int64

In [142]:
s1.index=[['류현진', '추신수', '투머치토커', '세리박']]

In [143]:
s1

류현진      2
추신수      4
투머치토커    6
세리박      8
dtype: int64

In [144]:
s1[0]

2

In [145]:
s1[2]

6

In [147]:
s1['류현진']
# 인덱스값에 접근할수있따

류현진    2
dtype: int64

In [152]:
s1.iloc[2]
# loc 앞에 i가 index를 뜻한다.
# loc = location

6

In [153]:
s1.loc['추신수']

추신수    4
dtype: int64

## 샘플데이터 활용

In [154]:
pd1 = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [156]:
type(pd1)

pandas.core.frame.DataFrame

In [157]:
pd1.shape

(3000, 9)

In [158]:
p = pd1.copy()

In [160]:
p
# 기본값 10개만 출력

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [161]:
p.head(3)
#앞에서 3개만 보기

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0

[3 rows x 9 columns]

In [162]:
p.tail(3)
#뒤에서 3개만 보기

longitude  latitude  ...  median_income  median_house_value
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3 rows x 9 columns]

In [196]:
pd2 = pd.read_csv('/content/sample_data/se.csv',encoding='cp949')

In [197]:
pd2

이순신  85  87  90
0  강감찬  75  80  95
1  한석봉  99  98  99
2  황진이  35  45  20
3  안중근  90  85  90
4  박문수  95  98  96
5  임꺽정  15  35  45
6  김정호  90  95  80
7  정몽주  90  90  95
8  오우석  50  45  60

In [179]:
# 일단 구했다 치고

p.shape

type(p)

p.ndim

p,size

p.info()

p.describe()

p.index

p.columns

p['총점'] = p['국어']+ p['영어'] + p['수학']

p['평균'] = p['총점'] / 3

p

In [188]:
pd2.shape

(9, 4)

In [211]:
pd3 = pd.read_csv('/content/sample_data/sc.csv',encoding='cp949')

In [212]:
pd3

이순신  85  87  90
0  강감찬  75  80  95
1  한석봉  99  98  99
2  황진이  35  45  20
3  안중근  90  85  90
4  박문수  95  98  96
5  임꺽정  15  35  45
6  김정호  90  95  80
7  정몽주  90  90  95
8  오우석  50  45  60

# 0행을 새로 추가하면서 파일을 불러온다.
#이후에 칼럼을 넣어줌

In [222]:
pd5 = pd.read_csv('/content/sample_data/sc.csv',encoding='cp949',header = None)

In [223]:
pd5

0   1   2   3
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  오우석  50  45  60

In [224]:
pd5.columns=['이름','국어','영어','수학']

In [225]:
pd5

이름  국어  영어  수학
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  오우석  50  45  60

In [226]:
pd5.mean()

국어    72.4
영어    75.8
수학    77.0
dtype: float64

In [229]:
pd5.loc[:,['국어','영어','수학']] >= 70

국어     영어     수학
0   True   True   True
1   True   True   True
2   True   True   True
3  False  False  False
4   True   True   True
5   True   True   True
6  False  False  False
7   True   True   True
8   True   True   True
9  False  False  False

In [230]:
pd5.iloc[:,1:] >= 70

국어     영어     수학
0   True   True   True
1   True   True   True
2   True   True   True
3  False  False  False
4   True   True   True
5   True   True   True
6  False  False  False
7   True   True   True
8   True   True   True
9  False  False  False

In [231]:
pd5.sum(axis=1)

0    262
1    250
2    296
3    100
4    265
5    289
6     95
7    265
8    275
9    155
dtype: int64

In [233]:
pd5['국어'].value_counts()
#점수 분포도?

90    3
95    1
75    1
15    1
85    1
99    1
50    1
35    1
Name: 국어, dtype: int64

In [234]:
pd5['국어'].value_counts(ascending=False)

90    3
95    1
75    1
15    1
85    1
99    1
50    1
35    1
Name: 국어, dtype: int64

In [235]:
pd5['국어'].sort_values()

6    15
3    35
9    50
1    75
0    85
4    90
7    90
8    90
5    95
2    99
Name: 국어, dtype: int64

In [236]:
pd5['국어'].sort_values(ascending=False)

2    99
5    95
8    90
7    90
4    90
0    85
1    75
9    50
3    35
6    15
Name: 국어, dtype: int64

In [237]:
pd5.sort_values(by='영어')
#영어점수 기준으로 줄세우기

이름  국어  영어  수학
6  임꺽정  15  35  45
3  황진이  35  45  20
9  오우석  50  45  60
1  강감찬  75  80  95
4  안중근  90  85  90
0  이순신  85  87  90
8  정몽주  90  90  95
7  김정호  90  95  80
2  한석봉  99  98  99
5  박문수  95  98  96

In [238]:
pd5.sort_values(by=['영어','수학'])
# 기준을 2가지
# 영어가 동점일떄 수학이 높은 순서로

이름  국어  영어  수학
6  임꺽정  15  35  45
3  황진이  35  45  20
9  오우석  50  45  60
1  강감찬  75  80  95
4  안중근  90  85  90
0  이순신  85  87  90
8  정몽주  90  90  95
7  김정호  90  95  80
5  박문수  95  98  96
2  한석봉  99  98  99

In [250]:
pd5.sort_values(by=['영어','수학'], inplace=True)

In [253]:
pd5['영어'] + 5
#영어 점수만 5점 더줘야할때

6     40
3     50
9     50
1     85
4     90
0     92
8     95
7    100
5    103
2    103
Name: 영어, dtype: int64

In [254]:
pd5

이름  국어  영어  수학
6  임꺽정  15  35  45
3  황진이  35  45  20
9  오우석  50  45  60
1  강감찬  75  80  95
4  안중근  90  85  90
0  이순신  85  87  90
8  정몽주  90  90  95
7  김정호  90  95  80
5  박문수  95  98  96
2  한석봉  99  98  99

###평균으로 수우미 양가


def get_grade(x):

        grade = ''

        if x >= 90: grade = '수'

        elif x >= 80: grade = '우'

        elif x >= 70: grade = '미'

        elif x >= 70: grade = '양'

        else: grade = '가'

        return grade

pd5['평가'] = pd5['평균'].apply(lambda x: get_grade(x))

pd5

#pandas column 추가하기

In [265]:
pd5['총점']=100
# 우측에 총점 항목으로 기본값 100을 입력

In [266]:
pd5

이름  국어  영어  수학  평균   총점
6  임꺽정  15  35  45  10  100
3  황진이  35  45  20  10  100
9  오우석  50  45  60  10  100
1  강감찬  75  80  95  10  100
4  안중근  90  85  90  10  100
0  이순신  85  87  90  10  100
8  정몽주  90  90  95  10  100
7  김정호  90  95  80  10  100
5  박문수  95  98  96  10  100
2  한석봉  99  98  99  10  100